# BEGIN ANSIBLE MANAGED BLOCK
version: "3"
networks:
  gitea:
    external: false
services:
  # Generate gitea cert for HTTPS
  prepare:
    container_name: gitea_pp
    image: registry.org:10443/library/gitea/gitea:1.17.2
    environment:
    - USER_UID=1000
    - USER_GID=1000
    volumes:
    - /home/kube/.kube-ansible/gitea/data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    command:
    - sh
    - -c
    - |
      su $$(getent passwd 1000 | cut -d : -f 1)
      mkdir -p /data/gitea
      cd /data/gitea
      if [ ! -f cert.pem ] || [ ! -f key.pem ]; then
        echo $$(date '+%Y/%m/%d %H:%M:%S') 'Generating certs...'
        gitea cert --host git.org,10.0.3.9 --duration 876000h0m0s --ca
      fi
  server:
    container_name: gitea
    image: registry.org:10443/library/gitea/gitea:1.17.2
    restart: always
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__DB_TYPE=postgres
    - GITEA__database__HOST=db:5432
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=gitea
    - GITEA__database__PASSWD=gitea
    
    - GITEA__server__PROTOCOL=https
    - GITEA__server__DOMAIN=git.org
    - GITEA__server__HTTP_PORT=11443
    - GITEA__server__ROOT_URL=https://localhost:11443/
    - GITEA__server__CERT_FILE=cert.pem
    - GITEA__server__KEY_FILE=key.pem
    - GITEA__server__OFFLINE_MODE=true
    networks:
    - gitea
    volumes:
    - /home/kube/.kube-ansible/gitea/data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "11443:11443"
    depends_on:
    - db
    - prepare
  db:
    container_name: gitea_db
    image: registry.org:10443/library/postgres:14
    restart: always
    environment:
    - POSTGRES_USER=gitea
    - POSTGRES_PASSWORD=gitea
    - POSTGRES_DB=gitea
    networks:
    - gitea
    volumes:
    - /home/kube/.kube-ansible/gitea/postgres:/var/lib/postgresql/data
# END ANSIBLE MANAGED BLOCK
