---
- hosts: node0
  gather_facts: no
  vars_files:
  - vars.yaml
  vars:
  - dir: "{{ cilium['temp_dir'] }}/chart"
  tasks:
  - name: Check release
    ansible.builtin.shell: helm list -n kube-system | grep cilium
    register: grep_cilium
    failed_when: grep_cilium.rc == 2

  - name: Clean
    ansible.builtin.file:
      path: "{{ dir }}"
      state: absent
    when: grep_cilium['stdout'].find("cilium") == -1

  - name: Get chart
    ansible.builtin.shell: helm pull cilium --repo https://helm.cilium.io --version {{ cilium['img_ver'] }} --untar --untardir {{ dir }}
    when: grep_cilium['stdout'].find("cilium") == -1

  - name: Collect image name
    ansible.builtin.shell: |
      helm template cilium {{ dir }}/cilium > {{ dir }}/rendered.yaml
      cat {{ dir }}/rendered.yaml | grep -e "^[ \t]*image:" | sed "s/[ \t]*image: \"*//" | cut -d '@' -f 1 > {{ dir }}/src-images
    when: grep_cilium['stdout'].find("cilium") == -1

  - name: Pull image
    ansible.builtin.shell: |
      linenum=$(wc -l {{ dir }}/src-images | cut -d ' ' -f 1)
      i=1
      while [ $i -le $linenum ]; do
        src=$(sed "$i!d;q" {{ dir }}/src-images)
        dest={{ registry['url'] }}/$src
        echo $dest >> {{ dir }}/dest-images
        repo=$(echo $dest | sed "s/{{ registry['url'] }}\///" | cut -d ':' -f 1)
        tag=$(echo $dest | sed "s/{{ registry['url'] }}\///" | cut -d ':' -f 2)
        existtags=$(curl -ks "https://{{ registry['url'] }}/v2/$repo/tags/list")
        if [ -z $(echo $existtags | grep $tag) ]; then
          docker image pull $src
          docker image tag $src $dest
          docker image push $dest
        fi
        i=$((i+1))
      done
    when: grep_cilium['stdout'].find("cilium") == -1

  - name: Change repository
    ansible.builtin.shell: |
      sed -i "s/repository: \"/repository: \"{{ registry['url'] }}\//" "{{ dir }}/cilium/values.yaml"
      sed -i "s/useDigest: true/useDigest: false/" "{{ dir }}/cilium/values.yaml"
    when: grep_cilium['stdout'].find("cilium") == -1

  - name: Install cilium
    ansible.builtin.shell: helm install cilium "{{ dir }}/cilium" -n kube-system
    when: grep_cilium['stdout'].find("cilium") == -1

- hosts: nodes
  gather_facts: no
  tasks:
  - name: Restart containerd
    become: yes
    ansible.builtin.shell: systemctl restart containerd
    when: hostvars['node0']['grep_cilium']['stdout'].find("cilium") == -1

