---
# Clean first
- import_playbook: cluster-reset.yaml

# Make cluter
- hosts: node0
  gather_facts: no
  tasks:
  - name: Make cluster
    become: yes
    ansible.builtin.shell: >
      echo "
      --cri-socket=/run/containerd/containerd.sock
      --pod-network-cidr=10.244.0.0/16
      --apiserver-advertise-address={{ hostvars['node0']['ansible_host'] }}
      --image-repository=registry.org:5000/k8s.gcr.io
      --kubernetes-version=v
TODO

