---
# Clean first
- import_playbook: cluster-reset.yaml

# Make cluter
- hosts: node0
  gather_facts: no
  tasks:
  - name: Make cluster
    become: yes
    ansible.builtin.shell: >
      kubeadm init
      -f
      --cri-socket=/run/containerd/containerd.sock
.....

