---
- hosts: dns0
  gather_facts: yes
  vars_files:
  - vars.yaml
  vars:
  - dir: "{{ coredns['dir'] }}"
  tasks:
  - name: Make sure the dirs exist
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
    - "{{ dir }}"
    - "{{ coredns['data'] }}"

  - name: Disable systemd-resolved
    become: yes
    ansible.builtin.shell: systemctl disable systemd-resolved --now

  - name: Back up the original resolv.conf and replace it
    become: yes
    ansible.builtin.shell: |
      if [ ! -L "/etc/resolv.conf.backup" ]; then
        mv /etc/resolv.conf /etc/resolv.conf.backup
        echo "nameserver 127.0.0.1" > {{ dir }}/resolv.conf
        ln -rsf {{ dir }}/resolv.conf /etc/resolv.conf
      fi

  - name: Make coredns Corefile
    ansible.builtin.blockinfile:
      path: "{{ coredns['data'] }}/Corefile"
      create: yes
      block: |
        (common) {
          log 
          errors
          reload
        }
        
        dn.tld {
          import common
          hosts /data/hosts
        }
        
        . {
          import common
          forward . 1.1.1.1 1.0.0.1
        }

  - name: Make coredns hosts file
    ansible.builtin.file:
      path: "{{ coredns['hosts'] }}"
      state: touch

  - name: Make coredns docker compose file
    ansible.builtin.blockinfile:
      path: "{{ dir }}/docker-compose.yaml"
      create: yes
      block: |
        version: "3"
        services:
          dns:
            container_name: coredns
            image: coredns/coredns:{{ coredns['ver'] }}
            restart: always
            ports:
            - 53:53
            - 53:53/udp
            volumes:
            - {{ coredns['data'] }}/:/data
            command: -conf /data/Corefile

  - name: Check coredns
    ansible.builtin.shell: docker compose -f {{ dir }}/docker-compose.yaml ps | grep coredns
    register: grep_coredns
    failed_when: grep_coredns['rc'] == 2

  - name: Run coredns
    ansible.builtin.shell: docker compose -f {{ dir }}/docker-compose.yaml up -d
    when: grep_coredns['rc'] == 1

