---
# Enable overlay & br_netfilter
- hosts: nodes
  gather_facts: no
  tasks:
  - name: Check conf file
    stat:
      path: /etc/modules-load.d/k8s.conf
    register: conffile
  - debug:
      msg: "conf file already exists, Next step will be skipped"
    when: conffile.stat.exists
  - name: Create /etc/modules-load.d/k8s.conf
    become: yes
    blockinfile:
      path: /etc/modules-load.d/k8s.conf
      create: yes
      block: |
        overlay
        br_netfilter
    when: not conffile.stat.exists
  - name: Load kerner modules
    become: yes
    shell: |
      modprobe overlay
      modprobe br_netfilter
    when: not conffile.stat.exists
  - name: Create /etc/sysctl.d/k8s.conf
    become: yes
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      create: yes
      block: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
    when: not conffile.stat.exists
  - name: Apply sysctl
    become: yes
    shell: sysctl --system
    when: not conffile.stat.exists
 
