---
- hosts: registry
  gather_facts: no
  tasks:
  - name: Install containerd
    ansible.builtin.import_tasks: containerd.yaml

  - name: Install docker
    ansible.builtin.import_tasks: docker.yaml

- name: Install coredns
  ansible.builtin.import_playbook: coredns.yaml

- name: Install envoy
  ansible.builtin.import_playbook: envoy.yaml

- name: Install harbor
  ansible.builtin.import_playbook: harbor.yaml

- name: Install gitea
  ansible.builtin.import_playbook: gitea.yaml

