---
# Install kube
- hosts: nodes
  gather_facts: no
  tasks:
  - package_facts:
      manager: auto
  - debug:
      msg: "kubelet is already installed. Next step will be skipped"
    when: "'kubelet' in ansible_facts.packages"
  - name: Install kube prerequisites
    become: yes
    apt:
      update_cache: yes
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
    when: "'kubelet' not in ansible_facts.packages"
  - name: Add apt repository
    become: yes
    shell: |
      curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
    when: "'kubelet' not in ansible_facts.packages"
  - name: Install kube
    become: yes
    apt:
      update_cache: yes
      pkg:
      - kubelet
      - kubeadm
      - kubectl
    when: "'kubelet' not in ansible_facts.packages"
  - name: Hold kube version
    become: yes
    shell: apt-mark hold kubelet kubeadm kubectl
    when: "'kubelet' not in ansible_facts.packages"

