---
# Install containerd
- hosts: nodes
  gather_facts: no
  tasks:
  - package_facts: # Get ansible_facts.packages object
      manager: auto
  - debug:
      msg: "containerd.io is already installed. Next step will be skipped"
    when: "'containerd.io' in ansible_facts.packages"
  - name: Install docker
    become: yes
    apt:
      update_cache: yes
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    when: "'containerd.io' not in ansible_facts.packages"
  - shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    when: "'containerd.io' not in ansible_facts.packages"
  - become: yes
    apt:
      update_cache: yes
      pkg:
      - containerd.io
    when: "'containerd.io' not in ansible_facts.packages"

# Install docker
- hosts: node0
  gather_facts: no
  tasks:
  - become: yes
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
    when: "'docker-ce' not in ansible_facts.packages"

