---
# Enable overlay & br_netfilter
- hosts: cluster
  gather_facts: no
  tasks:
  - name: Check kernel module conf file
    ansible.builtin.stat:
      path: /etc/modules-load.d/k8s.conf
    register: conffile

  - name: Create /etc/modules-load.d/k8s.conf
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/modules-load.d/k8s.conf
      create: yes
      block: |
        overlay
        br_netfilter
    when: not conffile['stat']['exists']

  - name: Load required kerner module now
    become: yes
    ansible.builtin.shell: |
      modprobe overlay
      modprobe br_netfilter
    when: not conffile['stat']['exists']

  - name: Create /etc/sysctl.d/k8s.conf
    become: yes
    ansible.builtin.blockinfile:
      path: /etc/sysctl.d/k8s.conf
      create: yes
      block: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
    when: not conffile['stat']['exists']

  - name: Apply sysctl
    become: yes
    ansible.builtin.shell: sysctl --system
    when: not conffile['stat']['exists']
 
