---
# Install kube
- hosts: nodes
  gather_facts: no
  tasks:
  - ansible.builtin.package_facts:
      manager: auto
  - ansible.builtin.debug:
      msg: "kubelet is already installed. Next step will be skipped"
    when: "'kubelet' in ansible_facts.packages"
  - name: Install kube prerequisites
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
    when: "'kubelet' not in ansible_facts.packages"
  - name: Add apt repository
    become: yes
    ansible.builtin.shell: |
      curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
    when: "'kubelet' not in ansible_facts.packages"
  - name: Install kube
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      pkg:
      - kubelet=1.24.4-00
      - kubeadm=1.24.4-00
      - kubectl=1.24.4-00
    when: "'kubelet' not in ansible_facts.packages"
  - name: Hold kube version
    become: yes
    ansible.builtin.shell: apt-mark hold kubelet kubeadm kubectl
    when: "'kubelet' not in ansible_facts.packages"
  - name: Apply bash autocompletion
    ansible.builtin.blockinfile:
      path: ~/.bashrc
      block: source <(kubectl completion bash)

