---
- ansible.builtin.package_facts:
    manager: apt

- ansible.builtin.import_tasks: wait-apt.yaml

- name: Install jq to parse json
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - jq
  when: "'jq' not in ansible_facts.packages"

- name: Wait for harbor to become ready
  ansible.builtin.shell: |
    t=0 
    wait=15
    try=12
    end=$((wait*try))
    while [ $t -lt $end ]; do
      ready=$(curl -ksu 'robot$kube':{{ harbor_pw }} https://{{ harbor['external'] }}/api/v2.0/health | jq -r .status)
      if [ "$ready" = "healthy" ]; then
        exit 0
      else
        sleep $wait
      fi
      t=$((t+wait))
    done
    exit 1
  vars:
    harbor_pw: "{{ lookup('file', '.keep/harbor-robot-kube-secret') }}"

- name: Login to harbor
  ansible.builtin.shell: docker login -u 'robot$kube' -p {{ harbor_pw }} {{ harbor['external'] }}
  vars:
    harbor_pw: "{{ lookup('file', '.keep/harbor-robot-kube-secret') }}"

