---
- name: Pull kube images
  ansible.builtin.import_playbook: kube-image.yaml

- name: Clean first
  ansible.builtin.import_playbook: cluster-reset.yaml

- name: Generate ssh key for sync
  ansible.builtin.import_playbook: ssh.yaml
  vars:
    key_sender: cp0
    key_receiver: cluster:!cp0

- name: Initialize cluter
  ansible.builtin.import_playbook: cluster-init.yaml

- name: Install helm
  ansible.builtin.import_playbook: helm.yaml

- name: Install cilium
  ansible.builtin.import_playbook: cilium.yaml

- name: Install cilium CLI
  ansible.builtin.import_playbook: cilium-cli.yaml

- name: Install metallb
  ansible.builtin.import_playbook: metallb.yaml

- name: Configure metallb
  ansible.builtin.import_playbook: metallb-conf.yaml

- name: Install dashboard
  ansible.builtin.import_playbook: dashboard.yaml

- name: Configure dashboard
  ansible.builtin.import_playbook: dashboard-conf.yaml

