---
- hosts: node0
  gather_facts: no
  vars_files:
  - vars.yaml
  vars:
  - dir: "{{ metallb['temp_dir'] }}/conf"
  tasks:
  - name: Make temp dir
    ansible.builtin.file:
      path: "{{ dir }}"
      state: directory

  - name: Make IPAddressPool and L2Advertisement yaml
    ansible.builtin.blockinfile:
      path: "{{ dir }}/metallb-conf.yaml"
      create: yes
      block: |
        ---
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: lb-ip-pool
          namespace: metallb-system
        spec:
          addresses:
          - "{{ metallb['ip_pool'] }}"

        ---
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: lb-l2-ad
          namespace: metallb-system
        spec:
          ipAddressPools:
          - lb-ip-pool

  - name: Wait for running metallb
    ansible.builtin.shell: |
      t=0
      wait=15
      try=6
      end=$((wait*try))
      while [ $t -lt $end ]; do
        ready=$(kubectl get pods -n metallb-system --no-headers=true -o custom-columns=:status.containerStatuses[*].ready | grep false)
        if [ -z "$ready" ]; then
          t=$end
        else
          sleep $wait
        fi
        t=$((t+wait))
      done

  - name: Apply metallb conf manifest
    ansible.builtin.shell: kubectl apply -f {{ dir }}/metallb-conf.yaml

