---
# Disable swapping on all nodes
- hosts: nodes
  gather_facts: no
  tasks:
  - name: Check swapping
    ansible.builtin.shell: cat /etc/fstab | grep swap
    register: fstab_swap

  - ansible.builtin.debug:
      msg: "Swapping is already disabled, Next step will be skipped"
    when: fstab_swap.stdout.find("#/swap") != -1

  - name: Disable swapping
    become: yes
    ansible.builtin.shell: |
      sed -i 's/\/swap/#\/swap/' /etc/fstab
      swapoff -a
    when: fstab_swap.stdout.find("#/swap") == -1
  
