---
# Set up SCM(git)
- hosts: git
  gather_facts: no
  tasks:
  - name: Add dns address to the hosts
    ansible.builtin.import_tasks: add-dns.yaml
  - name: Install containerd
    ansible.builtin.import_tasks: containerd.yaml
  - name: Install docker
    ansible.builtin.import_tasks: docker.yaml
- name: Install gitea
  ansible.builtin.import_playbook: gitea.yaml
- name: Configure gitea
  ansible.builtin.import_playbook: gitea-conf.yaml

# Set up CI(jenkins)
- hosts: ci
  gather_facts: no
  tasks:
  - name: Add dns address to the hosts
    ansible.builtin.import_tasks: add-dns.yaml
  - name: Install containerd
    ansible.builtin.import_tasks: containerd.yaml
  - name: Install docker
    ansible.builtin.import_tasks: docker.yaml
- name: Install jenkins
  ansible.builtin.import_playbook: jenkins.yaml
- name: Install jenkins plugins
  ansible.builtin.import_playbook: jenkins-plugins.yaml
- name: Configure jenkins
  ansible.builtin.import_playbook: jenkins-conf.yaml
- name: Make sample project
  ansible.builtin.import_playbook: jenkins-sample.yaml
- name: Restore jenkins secutiry options
  ansible.builtin.import_playbook: jenkins-restore-sec.yaml
  
