---
base:
  dir: "/home/{{ ansible_user }}/.kube-ansible"
  kube:
    ver: 1.24.6
  harbor:
    domain: registry.org
    port: 10443
    ver: 2.6.0
    pw: admin
  gitea:
    domain: git.dn.tld
    port: 11443
    ver: 1.17.2
    pg_ver: 14
    nginx_ver: 1.23.1
  cilium:
    cli:
      ver: 0.12.4
    img:
      ver: 1.12.2
  metallb:
    ver: 0.13.5
    ip_pool: 10.0.3.200-10.0.3.254
  dashboard:
    chart_ver: 5.10.0   
    ip: 10.0.3.254

containerd:
  dir: "{{ base['dir'] }}/containerd"

kubelet:
  apt_ver: "{{ base['kube']['ver'] }}-00"

kubeadm:
  dir: "{{ base['dir'] }}/kubeadm"
  apt_ver: "{{ base['kube']['ver'] }}-00"
  cmd_ver: "v{{ base['kube']['ver'] }}"

kubectl:
  apt_ver: "{{ base['kube']['ver'] }}-00"

harbor:
  dir: "{{ base['dir'] }}/harbor"
  ver: "v{{ base['harbor']['ver'] }}"
  domain: "{{ base['harbor']['domain'] }}"
  port: "{{ base['harbor']['port'] }}"
  url: "{{ base['harbor']['domain'] }}:{{ base['harbor']['port'] }}" 
  prj: "{{ base['harbor']['domain'] }}:{{ base['harbor']['port'] }}/library" 
  pw: "{{ base['harbor']['pw'] }}"

gitea:
  dir: "{{ base['dir'] }}/gitea"
  ver: "{{ base['gitea']['ver'] }}"
  domain: "{{ base['gitea']['domain'] }}"
  port: "{{ base['gitea']['port'] }}"
  url: "{{ base['gitea']['domain'] }}:{{ base['gitea']['port'] }}"
  pg_ver: "{{ base['gitea']['pg_ver'] }}"
  nginx_ver: "{{ base['gitea']['nginx_ver'] }}"

cilium:
  dir: "{{ base['dir'] }}/cilium"
  cli_ver: "v{{ base['cilium']['cli']['ver'] }}"
  img_ver: "{{ base['cilium']['img']['ver'] }}"

metallb:
  dir: "{{ base['dir'] }}/metallb"
  ver: "v{{ base['metallb']['ver'] }}" 
  ip_pool: "{{ base['metallb']['ip_pool'] }}"

dashboard:
  dir: "{{ base['dir'] }}/dashboard"
  ver: "{{ base['dashboard']['chart_ver'] }}"
  ip: "{{ base['dashboard']['ip'] }}"

