---
base:
  dir: "/home/{{ ansible_user }}/.kube-ansible"
  coredns:
    ver: 1.8.7
  envoy:
    domain: dn.tld
    ver: 1.23.1
    admin_port: 10001
  harbor:
    domain: harbor.registry
    port: 10443
    ver: 2.6.0
    pw: admin
  gitea:
    domain: gitea.git
    port: 11443
    ver: 1.17.2
    pg_ver: 14
    nginx_ver: 1.23.1
  jenkins:
    domain: jenkins.ci
    port: 12443
    ver: 2.373-jdk11
    docker_ver: 20.10.19-dind
    nginx_ver: 1.23.1
  kube:
    ver: 1.24.6
  cilium:
    cli:
      ver: 0.12.4
    img:
      ver: 1.12.2
  metallb:
    ver: 0.13.5
    ip_pool: 10.0.3.200-10.0.3.254
  dashboard:
    chart_ver: 5.10.0   
    ip: 10.0.3.254

coredns:
  dir: "{{ base['dir'] }}/coredns"
  data: "{{ base['dir'] }}/coredns/data"
  hosts: "{{ base['dir'] }}/coredns/data/hosts"
  ver: "{{ base['coredns']['ver'] }}"

envoy:
  dir: "{{ base['dir'] }}/envoy"
  ver: "v{{ base['envoy']['ver'] }}"
  domain: "{{ base['envoy']['domain'] }}"
  alt_names:
  - "{{ base['envoy']['domain'] }}"
  - "*.{{ base['envoy']['domain'] }}"
  admin_port: "{{ base['envoy']['admin_port'] }}"

harbor:
  dir: "{{ base['dir'] }}/harbor"
  ver: "v{{ base['harbor']['ver'] }}"
  domain: "{{ base['harbor']['domain'] }}"
  alt_names: ["{{ base['harbor']['domain'] }}"]
  port: "{{ base['harbor']['port'] }}"
  url: "{{ base['harbor']['domain'] }}:{{ base['harbor']['port'] }}" 
  prj: "{{ base['harbor']['domain'] }}:{{ base['harbor']['port'] }}/library" 
  external: "registry.{{ base['envoy']['domain'] }}"
  pw: "{{ base['harbor']['pw'] }}"

gitea:
  dir: "{{ base['dir'] }}/gitea"
  ver: "{{ base['gitea']['ver'] }}"
  domain: "{{ base['gitea']['domain'] }}"
  alt_names: ["{{ base['gitea']['domain'] }}"]
  port: "{{ base['gitea']['port'] }}"
  external: "git.{{ base['envoy']['domain'] }}"
  pg_ver: "{{ base['gitea']['pg_ver'] }}"
  nginx_ver: "{{ base['gitea']['nginx_ver'] }}"

jenkins:
  dir: "{{ base['dir'] }}/jenkins"
  ver: "{{ base['jenkins']['ver'] }}"
  domain: "{{ base['jenkins']['domain'] }}"
  alt_names: ["{{ base['jenkins']['domain'] }}"]
  port: "{{ base['jenkins']['port'] }}"
  external: "ci.{{ base['envoy']['domain'] }}"
  docker_ver: "{{ base['jenkins']['docker_ver'] }}"
  nginx_ver: "{{ base['jenkins']['nginx_ver'] }}"

containerd:
  dir: "{{ base['dir'] }}/containerd"

kubelet:
  apt_ver: "{{ base['kube']['ver'] }}-00"

kubeadm:
  dir: "{{ base['dir'] }}/kubeadm"
  apt_ver: "{{ base['kube']['ver'] }}-00"
  cmd_ver: "v{{ base['kube']['ver'] }}"

kubectl:
  apt_ver: "{{ base['kube']['ver'] }}-00"

cilium:
  dir: "{{ base['dir'] }}/cilium"
  cli_ver: "v{{ base['cilium']['cli']['ver'] }}"
  img_ver: "{{ base['cilium']['img']['ver'] }}"

metallb:
  dir: "{{ base['dir'] }}/metallb"
  ver: "v{{ base['metallb']['ver'] }}" 
  ip_pool: "{{ base['metallb']['ip_pool'] }}"

dashboard:
  dir: "{{ base['dir'] }}/dashboard"
  ver: "{{ base['dashboard']['chart_ver'] }}"
  ip: "{{ base['dashboard']['ip'] }}"

