---
- name: "{{ title }}"
  ansible.builtin.shell: |
    pw=$(cat {{ dir }}/jenkins/data/secrets/initialAdminPassword)
    t=0 
    wait=3
    try=20
    end=$((wait*try))
    while [ $t -lt $end ]; do
      code=$(curl -ksu admin:$pw -o /dev/null -w %{http_code} https://{{ jenkins['external'] }}{{ path }})
      if [ $code -eq {{ code }} ]; then
        exit 0
      else
        sleep $wait
      fi  
      t=$((t+wait))
    done
    exit 1
